#!/command/with-contenv bash
cd /home/jovyan/webapp
exec 2>&1

# Run Gunicorn with appropriate settings for reverse proxy
exec python -m gunicorn --bind 0.0.0.0:8888 \
  --forwarded-allow-ips="*" \
  --access-logfile=- \
  app:app
